# ip地址
spring:
  redis:
#    host: localhost
    host: 192.168.5.58
    port: 6379
    database: 0
#    password: password
    password: yibayi_181~jishubu*007
    timeout: 10000
    jedis:
      pool:
        max-idle: 300
        max-wait: 1000
        time-between-eviction-runs: 1024